app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

kcfinder:
    resource: "@IkadocKCFinderBundle/Resources/config/routing.yml"
    prefix: /