app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Main:homepage

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"