<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Users extends \AppBundle\Entity\Users implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'sname', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'info', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'hasFact', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'UsersType', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'UsersFacts', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'image'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'sname', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'email', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'info', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'hasFact', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'date', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'UsersType', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'UsersFacts', '' . "\0" . 'AppBundle\\Entity\\Users' . "\0" . 'image'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Users $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function _construct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '_construct', []);

        return parent::_construct();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getSname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSname', []);

        return parent::getSname();
    }

    /**
     * {@inheritDoc}
     */
    public function setSname($sname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSname', [$sname]);

        return parent::setSname($sname);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfo', []);

        return parent::getInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfo($info)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfo', [$info]);

        return parent::setInfo($info);
    }

    /**
     * {@inheritDoc}
     */
    public function gethasFact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gethasFact', []);

        return parent::gethasFact();
    }

    /**
     * {@inheritDoc}
     */
    public function sethasFact($hasFact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'sethasFact', [$hasFact]);

        return parent::sethasFact($hasFact);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersType', []);

        return parent::getUsersType();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsersType(\AppBundle\Entity\UsersType $UsersType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsersType', [$UsersType]);

        return parent::setUsersType($UsersType);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersFacts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersFacts', []);

        return parent::getUsersFacts();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsersFacts(\AppBundle\Entity\UsersFacts $UsersFacts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsersFacts', [$UsersFacts]);

        return parent::setUsersFacts($UsersFacts);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

}
